name: Trigger Target Repository Workflow

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  trigger-target-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Trigger Target Repository Workflow
        env:
          TARGET_REPO: Sakthi770/git-training  # Replace with the name of the target repository
          TARGET_WORKFLOW_NAME: check-environment.yml  # Replace with the name of the workflow to trigger in the target repository
        run: |
          # Set up the target repository and workflow name
          TARGET_REPO="${TARGET_REPO}"
          TARGET_WORKFLOW_NAME="${TARGET_WORKFLOW_NAME}"

          # Trigger the workflow in the target repository
     
          echo "repository=${TARGET_REPO}" >> $GITHUB_ENV
         
          echo "workflow=${TARGET_WORKFLOW_NAME}" >> $GITHUB_ENV
