name: Trigger Target Repository Workflow

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  trigger-target-workflow:
    runs-on: ubuntu-latest

    steps:

      #- name: Trigger Target Repository Workflow
       # id: trigger-workflow
        #env:
          #TARGET_REPO: Sakthi770/git-training/  # Replace with the name of the target repository
          #TARGET_WORKFLOW_NAME: check-environment.yml  # Replace with the name of the workflow to trigger in the target repository
        #run: |
          # Set up the target repository and workflow name
          #TARGET_REPO="${TARGET_REPO}"
          #TARGET_WORKFLOW_NAME="${TARGET_WORKFLOW_NAME}"

          # Trigger the workflow in the target repository
            #echo "::set-output name=repository::${TARGET_REPO}"
            #echo "{repository}=${TARGET_REPO}" >> $GITHUB_OUTPUT
          
            #echo "::set-output name=workflow::${TARGET_WORKFLOW_NAME}"
            #echo "{workflow}=${TARGET_WORKFLOW_NAME}" >> $GITHUB_OUTPUT

           #echo "GH_TOKEN=${{ secrets.ORG_ADMIN_TOKEN }}" >> $GITHUB_ENV
        
           #echo "Triggering ${{ steps.trigger-workflow.outputs.workflow }}" && gh workflow run ${{ steps.trigger-workflow.outputs.repository }}/${{ steps.trigger-workflow.outputs.workflow }}

          - name: Trigger Target Repository Workflow
            env:
              PAT_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}  # Personal Access Token with repo scope
              TARGET_REPO: https://github.com/Sakthi770/git-training/  # Replace with the name of the target repository
              TARGET_WORKFLOW_NAME: check-environment.yml  # Replace with the name of the workflow to trigger in the target repository
              REPO_NAME: ${{ github.event.repository.name }}
            run: |
              # Authenticate using the PAT_TOKEN
              gh auth login --with-token <<< "${PAT_TOKEN}"
    
              # Trigger the workflow in the target repository
              gh workflow run "$TARGET_WORKFLOW_NAME" -R "$TARGET_REPO" -F repo=$REPO_NAME
